Fix compilation error with -DLIBCXXABI_ENABLE_THREADS=OFF
The error is:

libcxxabi/src/cxa_guard_impl.h: In instantiation of ‘__cxxabiv1::{anonymous}::LibcppMutex __cxxabiv1::{anonymous}::GlobalStatic<__cxxabiv1::{anonymous}::LibcppMutex>::instance’:
libcxxabi/src/cxa_guard_impl.h:529:62:   required from here
libcxxabi/src/cxa_guard_impl.h:510:23: error: ‘__cxxabiv1::{anonymous}::LibcppMutex __cxxabiv1::{anonymous}::GlobalStatic<__cxxabiv1::{anonymous}::LibcppMutex>::instance’ has incomplete type
 _LIBCPP_SAFE_STATIC T GlobalStatic<T>::instance = {};
                       ^

git-svn-id: https://llvm.org/svn/llvm-project/libcxxabi/trunk@359175 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit f98261d3290e2b05e7714ba125d9315d87e9d62e)

Bug: http://b/189279320
Test: treehugger
Change-Id: Idf967a477590de8baf88541aff3aff08ff15e187